config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'}
  
  resources :users do
    member do
      patch :ban
      patch :resend_confirmation_instructions
      patch :resend_invitation
    end
  end
  root "static_pages#landing_page"
  get "privacy_policy", to: "static_pages#privacy_policy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/roleable.rb
module Roleable

  extend ActiveSupport::Concern 
  included do
    # List user roles
    ROLES = [:admin, :teacher, :student]
    
    #json column to store roles
    store_accessor :roles, *ROLES
    
    # Cast roles to/from booleans
    ROLES.each do |role|
      scope role, -> { where("roles @> ?", {role: true}.to_json) }
      define_method(:"#{role}=") { |value| super ActiveRecord::Type::Boolean.new.cast (value) }
      define_method(:"#{role}?") { send(role) } 
    end
    
    def active_roles # Where value true
      ROLES.select { |role| send(:"#{role}?") }.compact
    end
    
    # role validation
    validate :must_have_a_role, on: :update 
    validate :must_have_an_admin
    
    private
    
    def must_have_an_admin
      if persisted? &&
           (User.where.not(id: id).pluck(:roles).count { |h| h["admin"] == true } < 1) && 
           roles_changed? && admin == false 
        errors.add(:base, "There should be at least one admin")
      end 
    end
    
    def must_have_a_role
      if roles.values.none?
        errors.add(:base, "A user must have at least one role")
      end
    end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable, :lockable, :omniauthable, omniauth_providers: [:google_oauth2, :github, :facebook]
         

  include Roleable
  
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0,20]
         )
    end
    
    user.provider = access_token.provider
    user.uid = access_token.uid
    user.name = access_token.info.name
    user.save


    user.confirmed_at = Time.now
    user
  end 
  
  after_create do
    self.update(student: true)
  end
  
  def to_s
    email
  end
         
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
    def after_sign_in_path_for(resource)
        user_path(resource)
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    root_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def google_oauth2
    handle_auth 'Google'
  end
  
  def github
    handle_auth 'Github'
  end
  
  def facebook
    handle_auth 'Facebook'
  end
  
  def handle_auth(kind)
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
  
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  invisible_captcha only: [:create]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_admin, only: [:edit, :update, :ban, :destroy, :resend_confirmation_instructions]
  before_action :require_admin_or_inviter, only: [:resend_invitation]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def resend_confirmation_instructions
    @user = User.find(params[:id])
    if @user.confirmed? == false && @user.created_by_invite? == false
      @user.resend_confirmation_instructions
      redirect_to @user, notice: "Confirmation instructions were resent"
    else 
      redirect_to @user, notice: "User already confirmed"
    end
      
  end
  
  def resend_invitation
    @user = User.find(params[:id])
    if @user.created_by_invite? && @user.invitation_accepted? == false && @user.confirmed? == false
      @user.invite!
      redirect_to @user, notice: "Invitation was resent"
    else 
      redirect_to @user, notice: "User already confirmed"
    end
      
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else 
      render :edit
    end
  end
  
  def ban
    @user = User.find(params[:id])
    if @user.access_locked?
      @user.unlock_access!
    else
    @user.lock_access!
    end
    redirect_to @user, notice: "User ban status updated"
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: "User was successfully deleted"
  end
  
  private
  
  def user_params
    params.require(:user).permit(*User::ROLES)
  end
  
  def require_admin
    unless current_user.admin?
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
  
  def require_admin_or_inviter
    @user = User.find(params[:id])
    unless current_user.admin? || @user.invited_by == current.user
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def boolean_label(value)
    case value 
    when true
      content_tag(:span, value, class: "badge bg-success")
    when false
      content_tag(:span, value, class: "badge bg-danger")
    end 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def ban_status(user)
        if user.access_locked?
            "Unban"
        else
            "Ban"
        end
    end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fas fa-flag"></i>
      Brand
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do %>
          <div class="fa fa-home"></div>
          Home
        <% end %>
        <% if current_user %>
          <%= link_to users_path, class: "nav-link #{'active fw-bold' if current_page?(users_path)}" do %>
           <div class="fa fa-users"></div>
           Users
          <% end %>
          <%= link_to "Invite User", new_user_invitation_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_invitation_path)}" %>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="fa fa-user"></div>
              <b><%= current_user.email %></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              
              <%= link_to user_path(current_user), class: "dropdown-item #{'active fw-bold' if current_page?(user_path(current_user))}" do %>
                <div class="fa fa-user"></div>
                <b>My Profile</b>
              <% end %>
              
              <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% unless flash.empty? %>
   <script type="text/javascript">
      <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   	 toastr['<%= type %>']('<%= f[1] %>');
   <% end %>
   </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyGemsBootcamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    
    <%= render "layouts/header" %>
    <%= render "layouts/messages" %>

    <div class= "container">
      <br/>
    <%= yield %>
    </div>
  </body>
  <footer class= "bg-dark text-light">
    <div class= "container">
      Footer content
      <p>
       <%= link_to "Privacy Policy", privacy_policy_path %>
      </p>
    </div>
  </footer>
</html>

app/views/static_pages/landing_page.html.erb
<h1>Hello World</h1>
<%= link_to "Privacy policy", privacy_policy_path %>

<%= testing exception_notification %>

app/views/static_pages/privacy_policy.html.erb
<h1>StaticPages#privacy_policy</h1>
<%= link_to "Home", root_path %>

app/views/users/_user.html.erb
<strong>ID:</strong>
<%= link_to user.id, user_path(user) %>

<br/>

<strong>Email:</strong>
<%= user.email %>
    
<br/>

<strong>Confirmation:</strong>
<%= boolean_label(user.confirmed?) %>
<br/>

<% if user.sign_in_count? %>
    <b><%= 'sign_in_count'.humanize %>:</b>
    <%= user.sign_in_count %>
    <br/>
    <b><%= 'current_sign_in_at'.humanize %>:</b>
    <%= user.current_sign_in_at %>
    <br/>
    <b><%= 'last_sign_in_at'.humanize %>:</b>
    <%= user.last_sign_in_at %>
    <br/>
    <b><%= 'current_sign_in_ip'.humanize %>:</b>
    <%= user.current_sign_in_ip %>
    <br/>
    <b><%= 'last_sign_in_ip'.humanize %>:</b>
    <%= user.last_sign_in_ip %>
    <br/>
    <b><%= 'locked_at'.humanize %>:</b>
    <%= user.locked_at %>
    <br/>
    <b><%= 'provider'.humanize %>:</b>
    <%= user.provider %>
    <br/>
    <b><%= 'uid'.humanize %>:</b>
    <%= user.uid %>
    <br/>
    <b><%= 'name'.humanize %>:</b>
    <%= user.name %>
    <br/>
    <b><%= 'roles'.humanize %>:</b>
    <%= user.active_roles.join(",") %>
<% end %>
<br/>
<% if current_user.admin? %>
  <%= link_to "Edit roles", edit_user_path(user), class: "btn btn-sm btn-warning" %>
  <%= link_to ban_status(user), ban_user_path(user), class: "btn btn-sm btn-primary", method: :patch %>
  <%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-sm btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="card">
  <div class="card-header">
    <h2>
      Editing roles for <%= @user %>
    </h2>
  </div>
  
  <div class="card-body">
  <%= form_for(@user) do |f| %>
  
    <% if @user.errors.any? %> 
      ‹div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %>
          prohibited this user from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages. each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <% User::ROLES.each do |role| %>
      <label>
        <%= f.check_box role %>
        <%= role.to_s.humanize %> 
      </label> 
      <br>
    <% end %>
  
    <%= f.button :submit %>
  
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to "Cancel", user_path(@user) %>
  </div>
</div>

app/views/users/index.html.erb
<h2>
  Users:
  <%= @users.size %>
</h2>
<div class="table-responsive">
  <table class="table table-striped table-hover table-sm">
    <thead>
      <tr>
        <th>Id</th>
        <th>Email</th>
        <th>Confirmed</th>
        <th>Banned</th>
        <th>Name</th>
        <th>Roles</th>
        <th>Created by invitation?</th>
        <th>Invitation accepted?</th>
        <th>Invited by</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
  
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user. id, user_path(user) %></td>
          <td><%= user %></td>
          <td>
            <%= boolean_label(user.confirmed?) %>
          </td>
          <td><%= boolean_label(user.access_locked?) %></td>
          <td><%= user.name %></td>
          <td><%= user.active_roles.join(", ") %></td>
          <td><%= boolean_label(user.created_by_invite?) %></td>
          <td><%= boolean_label(user.invitation_accepted?) %></td>
          <td><%= user.invited_by %></td>
          <td>
            <% if current_user.admin? || user.invited_by == current_user %>
              <% if user.created_by_invite? && user.invitation_accepted? == false && user.confirmed? == false %>
                <%= link_to "Resend invitation", resend_invitation_user_path(user), method: :patch %>
              <% end %>
            <% end %>
            <% if current_user.admin? %>
              <% if user.confirmed? == false && user.created_by_invite? == false %>
                <%= link_to "Resend confirmation instructions", resend_confirmation_instructions_user_path(user), method: :patch, class: "btn btn-sm btn-secondary" %>
              <% end %>
              <%= link_to "Edit roles", edit_user_path(user), class: "btn btn-sm btn-warning" %>
              <%= link_to ban_status(user), ban_user_path(user), class: "btn btn-sm btn-primary", method: :patch %>
              <%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-sm btn-danger" %>
            <% end %>
          </td> 
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="card">

  <div class="card-body">
    <strong>ID:</strong>
    <%= link_to @user.id, user_path(@user) %>
    <br/>
  
    <strong>Email:</strong>
    <%= @user.email %>
        
    <br/>
    
    <strong>Confirmation:</strong>
    <%= boolean_label(@user.confirmed?) %>
    <br/>
    
    <% if @user.sign_in_count? %>
        <b><%= 'sign_in_count'.humanize %>:</b>
        <%= @user.sign_in_count %>
        <br/>
        <b><%= 'current_sign_in_at'.humanize %>:</b>
        <%= @user.current_sign_in_at %>
        <br/>
        <b><%= 'last_sign_in_at'.humanize %>:</b>
        <%= @user.last_sign_in_at %>
        <br/>
        <b><%= 'current_sign_in_ip'.humanize %>:</b>
        <%= @user.current_sign_in_ip %>
        <br/>
        <b><%= 'last_sign_in_ip'.humanize %>:</b>
        <%= @user.last_sign_in_ip %>
        <br/>
        <b><%= 'locked_at'.humanize %>:</b>
        <%= @user.locked_at %>
        <br/>
        <b><%= 'provider'.humanize %>:</b>
        <%= @user.provider %>
        <br/>
        <b><%= 'uid'.humanize %>:</b>
        <%= @user.uid %>
        <br/>
        <b><%= 'name'.humanize %>:</b>
        <%= @user.name %>
        <br/>
        <b><%= 'roles'.humanize %>:</b>
        <%= @user.active_roles.join(",") %>
    <% end %>
    <br/>
    <% if current_user.admin? %>
      <%= link_to "Edit roles", edit_user_path(@user), class: "btn btn-sm btn-warning" %>
      <%= link_to ban_status(@user), ban_user_path(@user), class: "btn btn-sm btn-primary", method: :patch %>
      <%= link_to "Delete", @user, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-sm btn-danger" %>
    <% end %>
  

  </div>
  <div class="card-footer">
    <%= link_to "All Users", users_path %>
  </div>
  
</div>
 